// Generated by CoffeeScript 1.8.0
(function(window) {
  var _CSSIsLoaded, _loadCSS, _p, _showOpenInPaw;
  if (window.paw) {
    return;
  }
  window.addEventListener("keydown", function(e) {
    var outer;
    if (e.keyCode === 27) {
      outer = document.getElementById("openinpaw-outer");
      if (outer) {
        outer.style.display = "none";
        e.preventDefault();
        return false;
      }
    }
  });
  _CSSIsLoaded = false;
  _loadCSS = function(href, onload) {
    "use strict";
    var ss;
    ss = window.document.createElement("link");
    ss.rel = "stylesheet";
    ss.href = href;
    ss.media = "all";
    ss.onload = onload;
    return document.getElementsByTagName("body")[0].appendChild(ss);
  };
  _showOpenInPaw = function(document_name, pawlink) {
    var _openInPawHTML, _showOuter;
    _openInPawHTML = function(document_name, pawlink) {
      return "<div class=\"openinpaw-middle\">\n	<div class=\"openinpaw\">\n		<div class=\"hd\">\n			<span class=\"appicon\"></span>\n			Open in <span class=\"appname\">Paw</span>\n		</div>\n		<div class=\"bd\">\n			<span class=\"dc\">Open \"" + document_name + "\" in Paw – the ultimate HTTP client for Mac.</span>\n			<div class=\"scc\"><span class=\"sc\"></span></div>\n			<div class=\"btnblk-container\">\n				<div class=\"btnblk\">\n					<span>Learn more about Paw</span>\n					<a href=\"https://luckymarmot.com/paw\" class=\"openinpaw-a-get\">Get Paw</a>\n				</div>\n				<div class=\"btnblk\">\n					<span>I already have Paw</span>\n					<a href=\"" + pawlink + "\" class=\"openinpaw-a-open\">Open in Paw</a>\n					<label>\n						<input name=\"name\" id=\"id\" type=\"checkbox\">\n						Always open in Paw\n					</span>\n				</div>\n				<div class=\"clr\"></div>\n			</div>\n		</div>\n	</div>\n</div>";
    };
    _showOuter = function() {
      var outer;
      outer = document.getElementById("openinpaw-outer");
      if (!outer) {
        outer = document.createElement("div");
        outer.id = outer.className = "openinpaw-outer";
        document.getElementsByTagName("body")[0].appendChild(outer);
      }
      outer.innerHTML = _openInPawHTML(document_name, pawlink);
      return outer.style.display = "";
    };
    if (_CSSIsLoaded) {
      return _showOuter();
    } else {
      _CSSIsLoaded = true;
      _loadCSS("http://fonts.googleapis.com/css?family=Open+Sans:400,300");
      return _loadCSS("http://localluckymarmot.com:8080/stylesheets/paw.css", function() {
        return _showOuter();
      });
    }
  };
  _p = {};
  _p.open = function(d) {
    if (d.deeplink) {
      return _showOpenInPaw(d.apiname || document.title, d.deeplink);
    } else if (d.a) {
      return _showOpenInPaw(d.apiname || d.a.getAttribute('data-paw-api-name') || document.title, d.a.href);
    }
  };
  window.paw = _p;
})(window);
